### ISSUE TITLE
[Bug]: Causes mouse cursor to stay on screen

### ISSUE THREAD

**Issue by TheDGOfficial** [ThatGravyBoat/RewardClaim#12]
### Bug Description

After clicking Claim Reward which claims the reward and closes the gui, the mouse cursor stays on screen till you restart the game.

This is in Linux Wayland, I'm not sure if it affects other platforms.

### How to Reproduce?

1. Open Daily Rewards menu
2. Pick a reward, hit Claim Reward
3. Menu closes, mouse cursor stays on screen

### Expected Behavior

I expect the cursor to go away.

### Version

2.1.1

### Mod Loader Version

Minecraft 1.21.8 - Fabric Loader 0.17.3

### Logs or additional context

Might be related or an issue specific to my platform (Linux Wayland) or my mods, I have one that prevents cursor position from ressetting in between menus, but that just saves prevX and prevY and restores that after closing a menu, shouldn't interfere with this I think. It also does not happen in any other menus be it server-side vanilla containers like chests / large chests or client-side mod ones (like profile viewer from skyblock mods). The mouse cursor only leaks from RewardClaim mod.

Once the issue happens, opening or closing any other server or client-side menus do not resolve the issue, which is weird, because I'd expect it to be hidden the next time a menu is closed. This pushes me even more towards it could be being a Wayland issue or something (Using the WayFix mod to force the game to run in Wayland natively over XWayland). Just creating this issue for tracking and to see if anyone else has the same issue.

I will try to troubleshoot the issue later, starting from the below lines which I presume handles the closing logic:

https://github.com/meowdding/RewardClaim/blob/23aad83eeefd67c26e8ae17a266f7d9c4985e388/src/main/kotlin/tech/thatgravyboat/rewardclaim/ui/RewardClaimScreen.kt#L63-L69

https://github.com/meowdding/RewardClaim/blob/23aad83eeefd67c26e8ae17a266f7d9c4985e388/src/main/kotlin/tech/thatgravyboat/rewardclaim/ui/RewardClaimScreen.kt#L129-L131

https://github.com/meowdding/RewardClaim/blob/23aad83eeefd67c26e8ae17a266f7d9c4985e388/src/main/kotlin/tech/thatgravyboat/rewardclaim/ui/RewardClaimScreens.kt#L30-L33

I'm not sure what mc.schedule does, is it used to add a 1 tick delay before closing, or is it used for thread-safety purposes to run the code in the render (client) thread? There's also a mc.send method, I would have to check the decompiled source code in my IDE later to see what kind of differences are there between the different methods.

Edit: Forgot to add but I'm also using the Ixeris mod which could interfere. Might try a test case with only RewardClaim mod installed later.

**Comment by TheDGOfficial** [comment]
This seems to happen even if you don't click anything and just press ESC to close the menu after opening. I did a little bit of code digging and found that ResourcefulLib has a call to GuiGraphics#requestCursor in CursorScreen.kt, so it might be related to that.

**Comment by TheDGOfficial** [comment]
> This seems to happen even if you don't click anything and just press ESC to close the menu after opening. I did a little bit of code digging and found that ResourcefulLib has a call to GuiGraphics#requestCursor in CursorScreen.kt, so it might be related to that.

Since then I found that code in ResourcefulLib to be used only on 1.21.10 version. 1.21.8 version calls glfwSetCursor manually, and when reverting to default cursor instead of setting the cursor to 0L (indicating a C NULL pointer), it sets it to a DEFAULT_CURSOR that's created with glfwCreateStandardCursor(GLFW.GLFW_ARROW_CURSOR). I have implemented a workaround for this bug in one of my mods, a "Cursor Fix" feature that sets cursor back to vanilla default after closing a menu, and it successfully fixes the issue in this mod (and possibly others using ResourcefulLib on 1.21.8. Not sure if 1.21.10 is affected since it uses GuiGraphics#requestCursor.)

Here's the code in case it would help anyone (changed it a bit for example purposes):
```java
package your.package;

import net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.gui.screen.Screen;
import org.jetbrains.annotations.Nullable;
import org.lwjgl.glfw.GLFW;

public final class CursorFix {
    @Nullable
    static Screen previousScreen;

    public static void init() {
        ClientTickEvents.END_CLIENT_TICK.register(client -> {
            var screen = client.currentScreen;

            if (null == screen && null != previousScreen) {
                // A screen was closed; reset the cursor to default.
                var windowId = client.getWindow().getHandle();
                GLFW.glfwSetCursor(windowId, 0L); // 0L equals to a C NULL pointer
            }

            previousScreen = screen;
        });
    }
}
```

Change your.package and call the CursorFix.init(); method from your mod entry point obviously.

Please let me know if this is fixed in 1.21.10 version of ResourcefulLib and no backport is planned for 1.21.8 so I can close this issue. I will be upgrading to 1.21.10 sooner or later when all my mods get updated so I will try to update it here whether it affects 1.21.10 or not by then, but for now it's unknown unless someone else tests so.

**Comment by ThatGravyBoat** [comment]
This is fixed in 1.21.10 if I get time I'll try and update 1.21.8 the issue is that in the reward screen it doesn't call the super for one of the removed or onClose methods which is what resets the cursor pack to default

**Comment by TheDGOfficial** [comment]
> This is fixed in 1.21.10 if I get time I'll try and update 1.21.8 the issue is that in the reward screen it doesn't call the super for one of the removed or onClose methods which is what resets the cursor pack to default

Indeed it's not an issue in 1.21.10, just tested. However, I think there's a different bug - the targeted block outline does not show with the RewardClaim mod installed, but it does show correctly if i remove the mod. I use the high contrast resourcepack/accessibility setting but even if i turn off that, it does not fix the issue. This seems to happen even in singleplayer and is in effect even before opening daily reward menu/joining hypixel.

The target block outline used to show perfectly fine with the mod installed in 1.21.8 (although it had the mouse sticking around bug.)

Any idea why it could be hiding targeted block outline in 1.21.10?

**Comment by ThatGravyBoat** [comment]
That's a bug with the bundled resourceful lib version if you manually added an updated version it will be fixed

**Comment by TheDGOfficial** [comment]
> That's a bug with the bundled resourceful lib version if you manually added an updated version it will be fixed

Indeed adding ResourcefulLib (v3.9.1) as a mod manually fixes the issue.

I did actually check ResourcefulLib changelog on Modrinth but it was just "Update to 1.21.5" so i thought the bundled version is fine. Now I see the fix commit looking at the commit history for v3.9.1 over at GitHub page.

Thanks for the help. Feel free to close this or keep it open till a release with updated bundled resourceful lib is made for both issues (cursor for 1.21.8 and targeted block outline for 1.21.10).

**Comment by TheDGOfficial** [comment]
I've went ahead and created a PR to bump implicitly bundled rlib to 3.9.1 for the targeted block outline fix in 1.21.10.

However, the cursor issue remains for the 1.21.8 version so I'll keep the issue open for now.
